package com.orbitai.erp.core.designsystem.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color

/**
 * Hue families a badge can be tinted with.
 *
 * These are colour names rather than domain states, and that is deliberate: `:core:designsystem`
 * has no business knowing what "awaiting QA sign-off" means. Mapping a `WorkStatus`, a `Severity`
 * or an audit action onto a tone is `:shared`'s job, in `ui/status/StatusTokens.kt`.
 */
enum class OrbitBadgeTone {
    Slate, Blue, Indigo, Violet, Cyan, Teal, Green, Amber, Orange, Red, Rose,
}

/**
 * The shades one badge needs, in one place.
 *
 * [label] and [icon] are separate colours and never equal — the icon sits a step further from the
 * fill than the text, which reads as intent rather than as a flat monochrome pill.
 *
 * [container] and [border] carry their own alpha. That translucency *is* the glass effect: the
 * card underneath tints through the pill instead of the pill sitting on top of it as an opaque
 * sticker. The cost is that contrast now depends on what is behind the badge, so every shade here
 * was verified against the fill composited over the most elevated surface in its theme
 * (`#E8E8E8` light, `#2A2A2A` dark) — the least favourable background a badge can land on.
 * `BadgeContrastTest` re-checks it on every build.
 *
 * Generated by `tools/gen_designsystem.py`. Do not edit by hand; the numbers are tuner output.
 */
@Immutable
data class OrbitBadgeColors(
    val container: Color,
    val border: Color,
    val label: Color,
    val icon: Color,
    /** Opaque fill for `OrbitBadgeEmphasis.Solid`, where a badge has to shout. */
    val solidContainer: Color,
    val onSolidContainer: Color,
)

internal val OrbitLightBadgeColors: Map<OrbitBadgeTone, OrbitBadgeColors> = mapOf(
    OrbitBadgeTone.Slate to OrbitBadgeColors(
        container = Color(0x42718198),
        border = Color(0x8C5A687C),
        label = Color(0xFF4B5768),
        icon = Color(0xFF404A59),
        solidContainer = Color(0xFF4D596A),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
    OrbitBadgeTone.Blue to OrbitBadgeColors(
        container = Color(0x42207EE9),
        border = Color(0x8C1365C3),
        label = Color(0xFF10529E),
        icon = Color(0xFF0D4687),
        solidContainer = Color(0xFF1157A7),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
    OrbitBadgeTone.Indigo to OrbitBadgeColors(
        container = Color(0x423B2CDD),
        border = Color(0x8C2B1EB8),
        label = Color(0xFF2B1EB8),
        icon = Color(0xFF261AA2),
        solidContainer = Color(0xFF251A9E),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
    OrbitBadgeTone.Violet to OrbitBadgeColors(
        container = Color(0x428531D8),
        border = Color(0x8C6B22B4),
        label = Color(0xFF6B22B4),
        icon = Color(0xFF5E1E9F),
        solidContainer = Color(0xFF5C1D9A),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
    OrbitBadgeTone.Cyan to OrbitBadgeColors(
        container = Color(0x4220C1E9),
        border = Color(0x8C13A0C3),
        label = Color(0xFF0C6379),
        icon = Color(0xFF0A5061),
        solidContainer = Color(0xFF1189A7),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Teal to OrbitBadgeColors(
        container = Color(0x4231D8C2),
        border = Color(0x8C22B4A1),
        label = Color(0xFF146B60),
        icon = Color(0xFF10564C),
        solidContainer = Color(0xFF1D9A8A),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Green to OrbitBadgeColors(
        container = Color(0x4239D078),
        border = Color(0x8C29AE60),
        label = Color(0xFF196B3B),
        icon = Color(0xFF145730),
        solidContainer = Color(0xFF239552),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Amber to OrbitBadgeColors(
        container = Color(0x42F0A919),
        border = Color(0x8CC98B0D),
        label = Color(0xFF7D5608),
        icon = Color(0xFF654506),
        solidContainer = Color(0xFFAD770B),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Orange to OrbitBadgeColors(
        container = Color(0x42EE731B),
        border = Color(0x8CC75C0F),
        label = Color(0xFF8E420B),
        icon = Color(0xFF773709),
        solidContainer = Color(0xFFAB4F0D),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
    OrbitBadgeTone.Red to OrbitBadgeColors(
        container = Color(0x42DF302A),
        border = Color(0x8CBA211C),
        label = Color(0xFF9B1C17),
        icon = Color(0xFF851814),
        solidContainer = Color(0xFFA01C18),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
    OrbitBadgeTone.Rose to OrbitBadgeColors(
        container = Color(0x42DA2F68),
        border = Color(0x8CB62052),
        label = Color(0xFF981B44),
        icon = Color(0xFF82173B),
        solidContainer = Color(0xFF9C1C46),
        onSolidContainer = Color(0xFFFFFFFF),
    ),
)

internal val OrbitDarkBadgeColors: Map<OrbitBadgeTone, OrbitBadgeColors> = mapOf(
    OrbitBadgeTone.Slate to OrbitBadgeColors(
        container = Color(0x5738414D),
        border = Color(0xA68F9CAE),
        label = Color(0xFFBEC5D0),
        icon = Color(0xFFCDD2DB),
        solidContainer = Color(0xFFACB6C3),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Blue to OrbitBadgeColors(
        container = Color(0x570C3F79),
        border = Color(0xA64F99EE),
        label = Color(0xFF99C4F5),
        icon = Color(0xFFB0D1F7),
        solidContainer = Color(0xFF7DB4F2),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Indigo to OrbitBadgeColors(
        container = Color(0x571B1372),
        border = Color(0xA66458E4),
        label = Color(0xFFADA7F1),
        icon = Color(0xFFC2BDF4),
        solidContainer = Color(0xFF8D84EB),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Violet to OrbitBadgeColors(
        container = Color(0x5742156F),
        border = Color(0xA69E5CE0),
        label = Color(0xFFC9A5EE),
        icon = Color(0xFFD6BAF2),
        solidContainer = Color(0xFFB887E8),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Cyan to OrbitBadgeColors(
        container = Color(0x570C6379),
        border = Color(0xA64FCEEE),
        label = Color(0xFF8BDFF4),
        icon = Color(0xFFA2E5F6),
        solidContainer = Color(0xFF7DDBF2),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Teal to OrbitBadgeColors(
        container = Color(0x57156F63),
        border = Color(0xA65CE0CE),
        label = Color(0xFF87E8DB),
        icon = Color(0xFF9CECE2),
        solidContainer = Color(0xFF87E8DB),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Green to OrbitBadgeColors(
        container = Color(0x57196B3B),
        border = Color(0xA662DA94),
        label = Color(0xFF94E6B6),
        icon = Color(0xFFA8EBC4),
        solidContainer = Color(0xFF8BE4B0),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Amber to OrbitBadgeColors(
        container = Color(0x577D5608),
        border = Color(0xA6F3BB49),
        label = Color(0xFFF7D082),
        icon = Color(0xFFF9D99A),
        solidContainer = Color(0xFFF6CD79),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Orange to OrbitBadgeColors(
        container = Color(0x577B3909),
        border = Color(0xA6F1904B),
        label = Color(0xFFF7BC92),
        icon = Color(0xFFF9CBAA),
        solidContainer = Color(0xFFF5AD7A),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Red to OrbitBadgeColors(
        container = Color(0x57731511),
        border = Color(0xA6E65B56),
        label = Color(0xFFF1A4A2),
        icon = Color(0xFFF4BAB8),
        solidContainer = Color(0xFFEC8683),
        onSolidContainer = Color(0xFF121212),
    ),
    OrbitBadgeTone.Rose to OrbitBadgeColors(
        container = Color(0x57711433),
        border = Color(0xA6E25A87),
        label = Color(0xFFEFA4BD),
        icon = Color(0xFFF3BACD),
        solidContainer = Color(0xFFEA86A7),
        onSolidContainer = Color(0xFF121212),
    ),
)

val OrbitBadgeTone.colors: OrbitBadgeColors
    @Composable @ReadOnlyComposable get() =
        (if (OrbitTheme.isDark) OrbitDarkBadgeColors else OrbitLightBadgeColors).getValue(this)

/**
 * The alphas the glass stack is drawn with.
 *
 * These live here, next to the palette, because they are not free parameters: the label and icon
 * shades above were tuned against exactly these values. Raising [Sheen] or a highlight without
 * regenerating the palette moves the background out from under text that was measured against it,
 * and `BadgeContrastTest` reproduces this stack precisely so that mistake fails the build.
 */
object OrbitGlass {
    /** Alpha multiplier applied to the fill along the top edge, fading to 1.0 at the bottom. */
    const val Sheen = 1.45f

    /** Peak alpha of the white highlight at the top edge of a badge. */
    const val BadgeHighlightLight = 0.22f
    const val BadgeHighlightDark = 0.1f

    /**
     * Peak alpha of the white highlight on a button.
     *
     * Lower than the badge values on purpose. A badge fill is translucent so its highlight competes
     * with whatever shows through; a button fill is opaque brand colour, and the badge figure would
     * wash a light-theme primary far enough to cost white label text its 4.5:1.
     */
    const val ButtonHighlightLight = 0.14f
    const val ButtonHighlightDark = 0.1f

    /**
     * Multiplier applied to a button's highlight while a pointer hovers it.
     *
     * The hovered top edge, not the resting one, is the brightest a button ever gets, so this is
     * part of the contrast budget: at this value white label text on a light-theme primary still
     * clears the minimum. It is verified alongside the palette.
     */
    const val ButtonHoverLift = 1.35f

    /**
     * Peak alpha of the white highlight on an icon button's ring.
     *
     * Modest on light and generous on dark, which is the opposite of the badge pair, because the
     * ring's fill is achromatic. Piling a white highlight onto a white fill buys nothing on light and
     * only risks blowing the top edge out; on a grey fill over a near-black page the same highlight is
     * the main thing saying the circle is glass rather than a flat grey dot.
     *
     * Neither figure is spent against a contrast budget the way the badge and button values are, since
     * the ring carries no text.
     */
    const val RingHighlightLight = 0.16f

    /**
     * Very low, and that is a fix rather than a compromise.
     *
     * A white highlight over the dark theme's grey ring fill produced a milky bloom across the top of
     * every circle - the fill is already a pale neutral, so adding white to it lightens the fill
     * instead of reading as light glancing off an edge. On light the same layer is harmless because
     * white over white is invisible; on dark it is the most visible thing in the component and it
     * looks like fog rather than glass.
     *
     * The glass read on dark is carried by the rim and the shadow instead, which are position and
     * material cues rather than a wash. This keeps just enough of the highlight to break the flatness
     * of the top edge.
     */
    const val RingHighlightDark = 0.05f

    /**
     * Alpha of the black contact shadow under a glass surface, per theme.
     *
     * Roughly triple on dark for the same visual weight. The dark surfaces start at `#121212` rather
     * than pure black, so there is headroom underneath them, but not much, and a shadow has to be far
     * deeper in alpha to register across it. See `Modifier.orbitGlassShadow` for why the answer is
     * never a lighter shadow.
     */
    const val ShadowLight = 0.16f
    const val ShadowDark = 0.48f

    /** How far the hairline edge fades from top to bottom, which is what gives the pill depth. */
    const val EdgeFade = 0.5f
}
